# Generated by Django 2.1 on 2021-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=50)),
                ('item1', models.CharField(blank=True, max_length=50)),
                ('item2', models.CharField(blank=True, max_length=50)),
                ('item3', models.CharField(blank=True, max_length=50)),
                ('url1', models.CharField(blank=True, max_length=50)),
                ('url2', models.CharField(blank=True, max_length=50)),
                ('url3', models.CharField(blank=True, max_length=50)),
                ('flag', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('flag', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
