# Generated by Django 2.1 on 2021-02-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=50)),
                ('stu_number', models.CharField(max_length=50)),
                ('stu_name', models.CharField(max_length=50)),
                ('flag', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=50)),
                ('day', models.IntegerField(null=True)),
                ('section', models.IntegerField(null=True)),
                ('lesson', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
