# Generated by Django 2.1 on 2021-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('claz', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=30)),
                ('tel', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('flag', models.IntegerField()),
                ('state', models.IntegerField(default=1)),
                ('subject', models.IntegerField(default=9)),
                ('remarks', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
